### ISSUE TITLE
GERBIL could not load file

### ISSUE THREAD

**Issue by ReleasedBrainiac** [AKSW/gerbil#175]
I created a file with the NIF converter pipline published by Michael Röder and got alot of working NIF files.
But needed to create a huge NIF file of a long annotated text and the resulting NIF couldnt be loaded by GERBIL. Please Help

[GoldTextWikipedia.zip](https://github.com/AKSW/gerbil/files/721954/GoldTextWikipedia.zip)

**Comment by MichaelRoeder** [comment]
```
Caused by: GerbilException: Exception while parsing dataset. (error type -104: The dataset couldn't be loaded.)
	at org.aksw.gerbil.dataset.impl.nif.AbstractNIFDataset.init(AbstractNIFDataset.java:103)
	at org.aksw.gerbil.dataset.impl.nif.NIFFileDatasetConfig.loadDataset(NIFFileDatasetConfig.java:39)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:59)
	at org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
	... 3 more
Caused by: org.apache.jena.atlas.RuntimeIOException: java.nio.charset.MalformedInputException: Input length = 1
	at org.apache.jena.atlas.io.IO.exception(IO.java:222)
	at org.apache.jena.atlas.io.CharStreamBuffered$SourceReader.fill(CharStreamBuffered.java:77)
	at org.apache.jena.atlas.io.CharStreamBuffered.fillArray(CharStreamBuffered.java:154)
	at org.apache.jena.atlas.io.CharStreamBuffered.advance(CharStreamBuffered.java:137)
	at org.apache.jena.atlas.io.PeekReader.advanceAndSet(PeekReader.java:241)
	at org.apache.jena.atlas.io.PeekReader.init(PeekReader.java:235)
	at org.apache.jena.atlas.io.PeekReader.peekChar(PeekReader.java:157)
	at org.apache.jena.atlas.io.PeekReader.makeUTF8(PeekReader.java:98)
	at org.apache.jena.riot.tokens.TokenizerFactory.makeTokenizerUTF8(TokenizerFactory.java:41)
	at org.apache.jena.riot.RiotReader.createParser(RiotReader.java:138)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:180)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:257)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:243)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:70)
	at org.aksw.gerbil.dataset.impl.nif.AbstractNIFDataset$LocalNIFParser.parseNIFModel(AbstractNIFDataset.java:158)
	at org.aksw.gerbil.io.nif.AbstractNIFParser.parseNIF(AbstractNIFParser.java:82)
	at org.aksw.gerbil.dataset.impl.nif.AbstractNIFDataset.init(AbstractNIFDataset.java:100)
	... 6 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	... 23 more
```

Please convert the file to `UTF-8` encoding to make it work.
```
numberOfDocuments=17103
numberOfEntities=37229
```

However, the parsing prints a lot of warnings. You might want to follow the description in the section https://github.com/AKSW/gerbil/wiki/Generating-a-NIF-dataset-using-Java#checking-the-created-nif to run the parsing locally and check the warnings.
