### ISSUE TITLE
Issue when starting

### ISSUE THREAD

**Issue by tgalery** [AKSW/gerbil#192]
After running `start.sh` I get this exception:

```
java.io.FileNotFoundException: gerbil_data/resources/hierarchies/DBpedia_DUL.ttl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.aksw.gerbil.semantic.subclass.ClassHierarchyLoader.readClassHierarchy(ClassHierarchyLoader.java:63)
	at org.aksw.gerbil.semantic.subclass.ClassHierarchyLoader.loadClassHierarchy(ClassHierarchyLoader.java:54)
	at org.aksw.gerbil.web.config.RootConfig.createSubClassInferencer(RootConfig.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:160)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1057)
```

**Comment by MichaelRoeder** [comment]
In older releases this file was missing. However, in version 1.2.5 it is inside the `gerbil_data.zip` file that is downloaded from https://github.com/AKSW/gerbil/releases/download/v1.2.5/gerbil_data.zip

I assume that you updated an older version of Gerbil to 1.2.5 and that since the `gerbil_data` folder exists the newer `gerbil_data.zip` file has not been downloaded. There are two ways to solve that problem.

1. You can remove your local `gerbil_data` folder and execute the `start.sh` script again. Note that this will also remove all your experiment results you might have created so far.

2. You can manually download the zip file using the link above and copy its content into the folder containing GERBIL.

Does it fix your problem?

**Comment by tgalery** [comment]
Many thanks @MichaelRoeder , your suggestion fixed it. But I'm still having problems running gerbil. I want to add an annotator as a service through the web ui. This annotator is running locally on localhost, but when I add it I get a 405 error even though I can connect to it normally via standard web interfaces (e.g. the browser). Is there any documentation on how to add an annotator (via uri or in some other way)

**Comment by MichaelRoeder** [comment]
> HTTP 405 - Method not allowed

Can you please make sure that your web service accepts `POST` messages? Most web services accept `GET` messages but might return this error coded if other methods are received. (Details about the communication can be found at https://github.com/AKSW/gerbil/wiki/How-to-create-a-NIF-based-web-service#communication )

**Comment by tgalery** [comment]
gotcha, I've managed to set up the experiment in another way, but I'm getting the following errors:

```
java.io.FileNotFoundException: /Users/thiago/source/gerbil/gerbil_data/cache/entityCheck.cache_temp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.performCacheStorage(FileBasedCachingEntityCheckerManager.java:213)
```
It seems that all the data got downloaded now. Am I doing something wrong ?

**Comment by MichaelRoeder** [comment]
No, sorry, that is a very stupid bug :smile: 

### Fast solution for you
Can you please go into the `gerbil_data` directory and create a `cache` folder?

### Hotfix solution for v1.2.5 (note for me)
Download and extract the `gerbil_data.zip` file. Create the dirctory and put a dummy file into it. Upload the updated `gerbil_data.zip` file.

### Better solution for the future (note for me)
Before writing the temporary cache file in https://github.com/AKSW/gerbil/blob/master/src/main/java/org/aksw/gerbil/dataset/check/impl/FileBasedCachingEntityCheckerManager.java#L213 the class should make sure that the directory exists. Otherwise, it should be created.

**Comment by tgalery** [comment]
Cool, testing it now!

**Comment by tgalery** [comment]
Ok, sorry to nag you @MichaelRoeder but I'm still having issues. I don't get the exception but after the experiment runs for a while I get this 
<img width="1251" alt="screen shot 2017-03-31 at 11 50 08" src="https://cloud.githubusercontent.com/assets/1846448/24547584/80207be6-1608-11e7-8e46-f5ba3c986c79.png">

To explain my situation a bit better. I'm running a custom version of spotlight on localhost. So my experiment is an Entity Recognition one (here I'm assuming is entity linking) and I've changed the uri in `annotators.properties` to point to my local host version. However, I don't see any requests being made against the localhost endpoint specified. Am I doing something wrong ?

**Comment by MichaelRoeder** [comment]
I assume that you changed the URL in this line https://github.com/AKSW/gerbil/blob/master/src/main/properties/annotators.properties#L50
Is that correct?
Btw. you might want ot set the flag in line 48 to false. Otherwise it won't reexecute successful experiments for 7 days.

The error looks strange to me because this message should only be visible if you restarted the server while the experiment was still running.
Could you please create a log file from the starting of the server until the experiment stops? I think 
`start.sh > gerbil.log` should work.
Can you please upload the file here? (if there are no private information, e.g., addresses or things like that)
